### ISSUE TITLE
xpc/xpc.h file not found.

### ISSUE THREAD

**Issue by partho-maple** [kokoabim/iOSOpenDev#107]
I am trying to create an XPC Service for iOS. I have created an XPC project from the template provided on iOSOpenDev Package. But i am getting xpc/xpc.h files not found error. Can someone please tell me that what i am missing or doing wrong ? Any help will be appreciated.

Thanks.

**Comment by npupyshev** [comment]
Just symlink this file from Mac OS SDK. However this template seems to cause problems
