### ISSUE TITLE
SSH Problem

### ISSUE THREAD

**Issue by ghost** [kokoabim/iOSOpenDev#109]
Now I know this isn't directly connected to iOSOpenDev, this seems to be the place to ask for help.
 I changed the @root SSH password on my iOS device (iPhone 5, iOS 7.0.4).
After I did that, iOSOpenDev wouldn't install to that device, giving me the following error:
http://i57.tinypic.com/2mmfmz6.png

So I thought it didn't get contact with the device, and tried to ssh into the device, which worked fine.
So I changed the password of the device back to what it was and tried again. Still the same error.

I tried multiple things:

ssh-keygen -R 10.0.0.170

cd ~/.ssh
ls
nano ~/.ssh/known_hosts

iosod sshkey -r 10.0.0.170

iosod update -h 10.0.0.170

Removing all the files in the «.shh» folder.

ssh-keygen (on the device).

And none of the above worked.
No matter what it kept saying "Public key is already authorized."
Now i'm left with a different error (Xcode):

Host key verification failed.

Failed to create directory /var/root/iOSOpenDevPackages on device 10.0.0.170
Command /bin/sh failed with exit code 255

How may I resolve this? It's driving me crazy.

**Comment by wbrickner** [comment]
You saved me from hours of frustration and google searches.
Thanks.
