### ISSUE TITLE
[Error] dpkg: status database area is locked by another process

### ISSUE THREAD

**Issue by albertschulz** [kokoabim/iOSOpenDev#117]
I experienced this error while running the script after building the application in XCode 6 when Cydia is running in background on iOS 8.

So to get rid of this, you need to kill cydia before the script installs the new .deb

1) Add this line in the build phases before the line `/opt/iOSOpenDev/bin/iosod --xcbp;`

`ssh root@DEVICE_IP "ps -U mobile | grep 'MobileCydia' | awk '{print \$1}' | awk 'NR==1' | xargs kill";`

2) Because iOS does not come with **ps** and **awk** you will need to install these packages in Cydia before:
- adv-cmds (for ps)
- Gawk (for awk)

**Comment by i0sa** [comment]
How did you manage to get iOSOpenDev work with iOS 8 and xCode 6.1
Its killing me with the arm64 thing, i updated libsubstrate ( from here http://sharedinstance.net/2013/12/how-to-support-arm64/ ) to support arm64 then i get this error 

ld: building for iOS Simulator, but linking against dylib built for MacOSX file '/opt/iOSOpenDev/lib/libsubstrate.dylib' for architecture x86_64

can't find any solution i did everything, can you tell me your settings, updates, requirements.. thanks.
