### ISSUE TITLE
App crashes at launch

### ISSUE THREAD

**Issue by agamirzov** [kokoabim/iOSOpenDev#121]
I converted my XCode 6 project to iOSOpenDev project with no issues. Now I'm trying to run my app on a device (iPhone 5 A1429, 8.1.2), but it crashes on the launch screen... I cannot see any crash reports from this app either... 

The app is a standard XCode Simple View template (I use it for testing), so I guess the problem is not the app itself... Any idea why it could be happening? Maybe I'm missing something?

Thank you!

**Comment by xyzdevdox** [comment]
i have the same problem.......
