### ISSUE TITLE
iPhoneOSPackageTypes.xcspec not found in Xcode 7

### ISSUE THREAD

**Issue by Razzile** [kokoabim/iOSOpenDev#130]
Probably the reason for everybody's "failed to install", iPhoneOSPackageTypes.xcspec is no longer in the Xcode app. Means that custom targets and other things cannot be added.

There is probably a workaround, I just haven't found it yet

**Comment by Noilednad** [comment]
same problem

**Comment by murrekatt** [comment]
same problem here
