### ISSUE TITLE
Error on iOSOpenDev 1.6-2 Installer // OS X 10.11.1

### ISSUE THREAD

**Issue by diegoquiroz** [kokoabim/iOSOpenDev#132]
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: LSExceptions [0x7fcf6b413f80] loaded
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: @(#)PROGRAM:Install  PROJECT:Install-1000
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: @(#)PROGRAM:Installer  PROJECT:Installer-853
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: Hardware: iMac14,2 @ 3.20 GHz (x 4), 10240 MB RAM
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: Running OS Build: Mac OS X 10.11.1 (15B42)
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: Env: __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x8
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: Env: TMPDIR=/var/folders/d2/b_m6dd953jl4xvw4r098sn_00000gn/T/
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: Env: HOME=/Users/Diego
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: Env: SHELL=/bin/bash
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: Env: SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.p5jyfdjF9B/Listeners
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: Env: Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.fs0PC57erR/Render
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: Env: PATH=/usr/bin:/bin:/usr/sbin:/sbin
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: Env: LOGNAME=Diego
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: Env: XPC_SERVICE_NAME=com.apple.xpc.launchd.oneshot.0x10000019.Installer
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: Env: COMMAND_MODE=unix2003
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: Env: USER=Diego
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: Env: XPC_FLAGS=0x0
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: iOSOpenDev (1.6-2)  Installation Log
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: Opened from: /Users/Diego/Downloads/iOSOpenDev-1.6-2.pkg
Dec  9 23:24:43 iMac-de-Diego Installer[2486]: Product archive /Users/Diego/Downloads/iOSOpenDev-1.6-2.pkg trustLevel=100
Dec  9 23:24:47 iMac-de-Diego Installer[2486]: InstallerStatusNotifications plugin loaded
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: Administrator authorization granted.
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: ================================================================================
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: User picked Standard Install
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: Choices selected for installation:
Dec  9 23:24:51 iMac-de-Diego Installer[2486]:  Instalar: "iOSOpenDev (1.6-2)"
Dec  9 23:24:51 iMac-de-Diego Installer[2486]:  Instalar: "Install iOSOpenDev and Set Up SDK"
Dec  9 23:24:51 iMac-de-Diego Installer[2486]:      iOSOpenDev-1.6-2.pkg#iodsetup.pkg : com.iosopendev.iosopendev162.iod-setup.pkg : 1.0
Dec  9 23:24:51 iMac-de-Diego Installer[2486]:  Instalar: "iOSOpenDev Uninstall Command-Line Tool"
Dec  9 23:24:51 iMac-de-Diego Installer[2486]:      iOSOpenDev-1.6-2.pkg#ioduninstall.pkg : com.iosopendev.iosopendev162.iod-uninstall.pkg : 1.0
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: ================================================================================
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: It took 0.00 seconds to summarize the package selections.
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/Diego/Downloads/iOSOpenDev-1.6-2.pkg#iodsetup.pkg
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/Diego/Downloads/iOSOpenDev-1.6-2.pkg#ioduninstall.pkg
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: Set authorization level to root for session
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: Will use PK session
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: Using authorization level of root for IFPKInstallElement
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: Starting installation:
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: Configuring volume "Macintosh HD"
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: Preparing disk for local booted install.
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: Free space on "Macintosh HD": 878.37 GB (878366113792 bytes).
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: Create temporary directory "/var/folders/d2/b_m6dd953jl4xvw4r098sn_00000gn/T//Install.2486CCb9bW"
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: IFPKInstallElement (2 packages)
Dec  9 23:24:51 iMac-de-Diego installd[425]: PackageKit: Adding client PKInstallDaemonClient pid=2486, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Dec  9 23:24:51 iMac-de-Diego Installer[2486]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
Dec  9 23:24:51 iMac-de-Diego installd[425]: PackageKit: ----- Begin install -----
Dec  9 23:24:51 iMac-de-Diego installd[425]: PackageKit: request=PKInstallRequest <2 packages, destination=/>
Dec  9 23:24:51 iMac-de-Diego installd[425]: PackageKit: packages=(
        "PKLeopardPackage file://localhost/Users/Diego/Downloads/iOSOpenDev-1.6-2.pkg#iodsetup.pkg",
        "PKLeopardPackage file://localhost/Users/Diego/Downloads/iOSOpenDev-1.6-2.pkg#ioduninstall.pkg"
    )
Dec  9 23:24:51 iMac-de-Diego installd[425]: PackageKit: Extracting file://localhost/Users/Diego/Downloads/iOSOpenDev-1.6-2.pkg#iodsetup.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/F416414E-22FE-49CD-822E-0AEE74C20BEB.activeSandbox/Root/opt/iOSOpenDevSetup/bin, uid=0)
Dec  9 23:24:51 iMac-de-Diego installd[425]: PackageKit: Extracting file://localhost/Users/Diego/Downloads/iOSOpenDev-1.6-2.pkg#ioduninstall.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/F416414E-22FE-49CD-822E-0AEE74C20BEB.activeSandbox/Root/opt/iOSOpenDevUninstall/bin, uid=0)
Dec  9 23:24:51 iMac-de-Diego installd[425]: PackageKit: prevent user idle system sleep
Dec  9 23:24:51 iMac-de-Diego installd[425]: PackageKit: suspending backupd
Dec  9 23:24:51 iMac-de-Diego installd[425]: PackageKit: Executing script "./preinstall" in /private/tmp/PKInstallSandbox.ugyCWl/Scripts/com.iosopendev.iosopendev162.iod-setup.pkg.m85YxH
Dec  9 23:24:51 iMac-de-Diego installd[425]: PackageKit: Executing script "./preinstall" in /private/tmp/PKInstallSandbox.ugyCWl/Scripts/com.iosopendev.iosopendev162.iod-uninstall.pkg.VUJeKg
Dec  9 23:24:51 iMac-de-Diego install_monitor[2489]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Dec  9 23:24:51 iMac-de-Diego installd[425]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/F416414E-22FE-49CD-822E-0AEE74C20BEB.sandboxTrash for sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/F416414E-22FE-49CD-822E-0AEE74C20BEB.activeSandbox
Dec  9 23:24:51 iMac-de-Diego installd[425]: PackageKit: Shoving /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/F416414E-22FE-49CD-822E-0AEE74C20BEB.activeSandbox/Root (1 items) to /
Dec  9 23:24:51 iMac-de-Diego installd[425]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.ugyCWl/Scripts/com.iosopendev.iosopendev162.iod-setup.pkg.m85YxH
Dec  9 23:24:51 iMac-de-Diego installd[425]: ./postinstall: Running /opt/iOSOpenDevSetup/bin/iod-setup...
Dec  9 23:24:51 iMac-de-Diego installd[425]: ./postinstall: Downloading iOSOpenDev base from Github...
Dec  9 23:24:53 iMac-de-Diego installd[425]: ./postinstall: Downloading Xcode templates from Github...
Dec  9 23:24:53 iMac-de-Diego Installer[2486]: LSExceptions [0x7fcf6b413f80] unloaded
Dec  9 23:24:55 iMac-de-Diego installd[425]: ./postinstall: Creating symlink to Xcode templates...
Dec  9 23:24:55 iMac-de-Diego installd[425]: ./postinstall: Modifying Bash personal initialization file...
Dec  9 23:24:55 iMac-de-Diego installd[425]: ./postinstall: Setting up iPhoneOS 9.1 SDK...
Dec  9 23:24:55 iMac-de-Diego installd[425]: ./postinstall: Modifying SDK settings...
Dec  9 23:24:56 iMac-de-Diego installd[425]: ./postinstall: Symlinking to private frameworks header files...
Dec  9 23:24:56 iMac-de-Diego installd[425]: ./postinstall: Adding specifications to platform...
Dec  9 23:24:56 iMac-de-Diego installd[425]: ./postinstall: File not found: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/Specifications/iPhoneOSPackageTypes.xcspec
Dec  9 23:24:56 iMac-de-Diego install_monitor[2489]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Dec  9 23:24:57 iMac-de-Diego installd[425]: PackageKit: releasing backupd
Dec  9 23:24:57 iMac-de-Diego installd[425]: PackageKit: allow user idle system sleep
Dec  9 23:24:57 iMac-de-Diego installd[425]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "Se ha producido un error al ejecutar scripts desde el paquete “iOSOpenDev-1.6-2.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/Diego/Downloads/iOSOpenDev-1.6-2.pkg#iodsetup.pkg, PKInstallPackageIdentifier=com.iosopendev.iosopendev162.iod-setup.pkg, NSLocalizedDescription=Se ha producido un error al ejecutar scripts desde el paquete “iOSOpenDev-1.6-2.pkg”.} {
        NSFilePath = "./postinstall";
        NSLocalizedDescription = "Se ha producido un error al ejecutar scripts desde el paquete \U201ciOSOpenDev-1.6-2.pkg\U201d.";
        NSURL = "file://localhost/Users/Diego/Downloads/iOSOpenDev-1.6-2.pkg#iodsetup.pkg";
        PKInstallPackageIdentifier = "com.iosopendev.iosopendev162.iod-setup.pkg";
    }
Dec  9 23:24:57 iMac-de-Diego installd[425]: PackageKit: Running idle tasks
Dec  9 23:24:57 iMac-de-Diego Installer[2486]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "Se ha producido un error al ejecutar scripts desde el paquete “iOSOpenDev-1.6-2.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/Diego/Downloads/iOSOpenDev-1.6-2.pkg#iodsetup.pkg, PKInstallPackageIdentifier=com.iosopendev.iosopendev162.iod-setup.pkg, NSLocalizedDescription=Se ha producido un error al ejecutar scripts desde el paquete “iOSOpenDev-1.6-2.pkg”.}
Dec  9 23:24:57 iMac-de-Diego installd[425]: PackageKit: Removing client PKInstallDaemonClient pid=2486, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Dec  9 23:24:57 iMac-de-Diego installd[425]: PackageKit: Done with sandbox removals
Dec  9 23:24:57 iMac-de-Diego installd[425]: PackageKit: Sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/B4677403-0D85-41D7-89D0-EA2F86E9A8DC.sandbox: relevance 308
Dec  9 23:24:57 iMac-de-Diego Installer[2486]: Install failed: El Instalador ha detectado un error que ha impedido completar la instalación. Póngase en contacto con el fabricante del software para solicitar ayuda.
Dec  9 23:24:57 iMac-de-Diego Installer[2486]: IFDInstallController 6B74B6F0 state = 8
Dec  9 23:24:57 iMac-de-Diego Installer[2486]: Displaying 'Install Failed' UI.
Dec  9 23:24:57 iMac-de-Diego Installer[2486]: 'Install Failed' UI displayed message:'El Instalador ha detectado un error que ha impedido completar la instalación. Póngase en contacto con el fabricante del software para solicitar ayuda.'.

---

I tried on a different mac and does not work

**Comment by 535064094** [comment]
same issue to you, I'm installed dpkg and theos,and they all on the /opt/ 
but still not working, I'm OS X 10.11.1 too. Xcode version 7.2

the logs show:
Dec 24 10:21:50 localhost Installer[5139]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "运行软件包“iOSOpenDev-1.6-2-2.pkg”的脚本时出错。" UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/sunjiaqi/Downloads/iOSOpenDev-1.6-2-2.pkg#iodsetup.pkg, PKInstallPackageIdentifier=com.iosopendev.iosopendev162.iod-setup.pkg, NSLocalizedDescription=运行软件包“iOSOpenDev-1.6-2-2.pkg”的脚本时出错。}

Is there anyone who knows how to fix that problem?

**Comment by 535064094** [comment]
I'm already installed success，(OS X 10.11.1 Xcode 7.2 ),here's the dealing. my english is too bad that i can't write it by english immediately,so there only chinese:
http://blog.csdn.net/u013583789/article/details/50396747
 i will upload english soon

**Comment by felipebueno** [comment]
Thanks, @535064094 I'll try that out.

Here's an english version: https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=pt-BR&ie=UTF-8&u=http%3A%2F%2Fblog.csdn.net%2Fu013583789%2Farticle%2Fdetails%2F50396747&edit-text=&act=url
