### ISSUE TITLE
1.6-2 install failed

### ISSUE THREAD

**Issue by cameloper** [kokoabim/iOSOpenDev#134]
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: LSExceptions [0x7f98e3711420] loaded
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: @(#)PROGRAM:Install  PROJECT:Install-1000
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: @(#)PROGRAM:Installer  PROJECT:Installer-853
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: Hardware: MacBookPro10,1 @ 2.70 GHz (x 8), 16384 MB RAM
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: Running OS Build: Mac OS X 10.11.2 (15C50)
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: Env: __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: Env: TMPDIR=/var/folders/hg/1xvnr31n6rsgdbnqdjbs21g40000gn/T/
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: Env: HOME=/Users/cameloper
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: Env: SHELL=/bin/bash
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: Env: SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.ETjqHp1Cn1/Listeners
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: Env: Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.l2XJK82429/Render
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: Env: PATH=/usr/bin:/bin:/usr/sbin:/sbin
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: Env: LOGNAME=cameloper
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: Env: XPC_SERVICE_NAME=com.apple.xpc.launchd.oneshot.0x10000010.Installer
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: Env: COMMAND_MODE=unix2003
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: Env: USER=cameloper
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: Env: XPC_FLAGS=0x0
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: iOSOpenDev (1.6-2)  Installation Log
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: Opened from: /Users/cameloper/Downloads/iOSOpenDev-1.6-2.pkg
Feb  3 15:12:50 camelopers-MacBook-Pro Installer[6702]: Product archive /Users/cameloper/Downloads/iOSOpenDev-1.6-2.pkg trustLevel=100
Feb  3 15:12:54 camelopers-MacBook-Pro Installer[6702]: InstallerStatusNotifications plugin loaded
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: Administrator authorization granted.
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: ================================================================================
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: User picked Standard Install
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: Choices selected for installation:
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]:     Install: "iOSOpenDev (1.6-2)"
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]:     Install: "Install iOSOpenDev and Set Up SDK"
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]:         iOSOpenDev-1.6-2.pkg#iodsetup.pkg : com.iosopendev.iosopendev162.iod-setup.pkg : 1.0
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]:     Install: "iOSOpenDev Uninstall Command-Line Tool"
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]:         iOSOpenDev-1.6-2.pkg#ioduninstall.pkg : com.iosopendev.iosopendev162.iod-uninstall.pkg : 1.0
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: ================================================================================
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: It took 0.00 seconds to summarize the package selections.
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/cameloper/Downloads/iOSOpenDev-1.6-2.pkg#iodsetup.pkg
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/cameloper/Downloads/iOSOpenDev-1.6-2.pkg#ioduninstall.pkg
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: Set authorization level to root for session
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: Will use PK session
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: Using authorization level of root for IFPKInstallElement
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: Starting installation:
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: Configuring volume "Macintosh HD"
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: Preparing disk for local booted install.
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: Free space on "Macintosh HD": 103,16 GB (103163899904 bytes).
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: Create temporary directory "/var/folders/hg/1xvnr31n6rsgdbnqdjbs21g40000gn/T//Install.6702PpaeyK"
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: IFPKInstallElement (2 packages)
Feb  3 15:12:59 camelopers-MacBook-Pro installd[304]: PackageKit: Adding client PKInstallDaemonClient pid=6702, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Feb  3 15:12:59 camelopers-MacBook-Pro Installer[6702]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
Feb  3 15:12:59 camelopers-MacBook-Pro installd[304]: PackageKit: ----- Begin install -----
Feb  3 15:12:59 camelopers-MacBook-Pro installd[304]: PackageKit: request=PKInstallRequest <2 packages, destination=/>
Feb  3 15:12:59 camelopers-MacBook-Pro installd[304]: PackageKit: packages=(
        "PKLeopardPackage file://localhost/Users/cameloper/Downloads/iOSOpenDev-1.6-2.pkg#iodsetup.pkg",
        "PKLeopardPackage file://localhost/Users/cameloper/Downloads/iOSOpenDev-1.6-2.pkg#ioduninstall.pkg"
    )
Feb  3 15:12:59 camelopers-MacBook-Pro installd[304]: PackageKit: Extracting file://localhost/Users/cameloper/Downloads/iOSOpenDev-1.6-2.pkg#iodsetup.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/DFBC0037-4858-474F-8369-A8256203FA2D.activeSandbox/Root/opt/iOSOpenDevSetup/bin, uid=0)
Feb  3 15:12:59 camelopers-MacBook-Pro installd[304]: PackageKit: Extracting file://localhost/Users/cameloper/Downloads/iOSOpenDev-1.6-2.pkg#ioduninstall.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/DFBC0037-4858-474F-8369-A8256203FA2D.activeSandbox/Root/opt/iOSOpenDevUninstall/bin, uid=0)
Feb  3 15:12:59 camelopers-MacBook-Pro installd[304]: PackageKit: prevent user idle system sleep
Feb  3 15:12:59 camelopers-MacBook-Pro installd[304]: PackageKit: suspending backupd
Feb  3 15:12:59 camelopers-MacBook-Pro installd[304]: PackageKit: Executing script "./preinstall" in /private/tmp/PKInstallSandbox.TlFarX/Scripts/com.iosopendev.iosopendev162.iod-setup.pkg.rWyRi3
Feb  3 15:12:59 camelopers-MacBook-Pro installd[304]: PackageKit: Executing script "./preinstall" in /private/tmp/PKInstallSandbox.TlFarX/Scripts/com.iosopendev.iosopendev162.iod-uninstall.pkg.A3zxLm
Feb  3 15:13:00 camelopers-MacBook-Pro install_monitor[6706]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Feb  3 15:13:00 camelopers-MacBook-Pro installd[304]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/DFBC0037-4858-474F-8369-A8256203FA2D.sandboxTrash for sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/DFBC0037-4858-474F-8369-A8256203FA2D.activeSandbox
Feb  3 15:13:00 camelopers-MacBook-Pro installd[304]: PackageKit: Shoving /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/DFBC0037-4858-474F-8369-A8256203FA2D.activeSandbox/Root (1 items) to /
Feb  3 15:13:00 camelopers-MacBook-Pro installd[304]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.TlFarX/Scripts/com.iosopendev.iosopendev162.iod-setup.pkg.rWyRi3
Feb  3 15:13:00 camelopers-MacBook-Pro installd[304]: ./postinstall: Running /opt/iOSOpenDevSetup/bin/iod-setup...
Feb  3 15:13:00 camelopers-MacBook-Pro installd[304]: ./postinstall: Downloading iOSOpenDev base from Github...
Feb  3 15:13:00 camelopers-MacBook-Pro Installer[6702]: LSExceptions [0x7f98e3711420] unloaded
Feb  3 15:13:02 camelopers-MacBook-Pro installd[304]: ./postinstall: Downloading Xcode templates from Github...
Feb  3 15:13:04 camelopers-MacBook-Pro installd[304]: ./postinstall: Creating symlink to Xcode templates...
Feb  3 15:13:04 camelopers-MacBook-Pro installd[304]: ./postinstall: Modifying Bash personal initialization file...
Feb  3 15:13:05 camelopers-MacBook-Pro installd[304]: ./postinstall: Setting up iPhoneOS 9.2 SDK...
Feb  3 15:13:05 camelopers-MacBook-Pro installd[304]: ./postinstall: Modifying SDK settings...
Feb  3 15:13:05 camelopers-MacBook-Pro installd[304]: ./postinstall: Symlinking to private frameworks header files...
Feb  3 15:13:06 camelopers-MacBook-Pro installd[304]: ./postinstall: Adding specifications to platform...
Feb  3 15:13:06 camelopers-MacBook-Pro installd[304]: ./postinstall: File not found: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/Specifications/iPhoneOSPackageTypes.xcspec
Feb  3 15:13:06 camelopers-MacBook-Pro install_monitor[6706]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Feb  3 15:13:07 camelopers-MacBook-Pro installd[304]: PackageKit: releasing backupd
Feb  3 15:13:07 camelopers-MacBook-Pro installd[304]: PackageKit: allow user idle system sleep
Feb  3 15:13:07 camelopers-MacBook-Pro installd[304]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “iOSOpenDev-1.6-2.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/cameloper/Downloads/iOSOpenDev-1.6-2.pkg#iodsetup.pkg, PKInstallPackageIdentifier=com.iosopendev.iosopendev162.iod-setup.pkg, NSLocalizedDescription=An error occurred while running scripts from the package “iOSOpenDev-1.6-2.pkg”.} {
        NSFilePath = "./postinstall";
        NSLocalizedDescription = "An error occurred while running scripts from the package \U201ciOSOpenDev-1.6-2.pkg\U201d.";
        NSURL = "file://localhost/Users/cameloper/Downloads/iOSOpenDev-1.6-2.pkg#iodsetup.pkg";
        PKInstallPackageIdentifier = "com.iosopendev.iosopendev162.iod-setup.pkg";
    }
Feb  3 15:13:07 camelopers-MacBook-Pro installd[304]: PackageKit: Running idle tasks
Feb  3 15:13:07 camelopers-MacBook-Pro Installer[6702]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “iOSOpenDev-1.6-2.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/cameloper/Downloads/iOSOpenDev-1.6-2.pkg#iodsetup.pkg, PKInstallPackageIdentifier=com.iosopendev.iosopendev162.iod-setup.pkg, NSLocalizedDescription=An error occurred while running scripts from the package “iOSOpenDev-1.6-2.pkg”.}
Feb  3 15:13:07 camelopers-MacBook-Pro installd[304]: PackageKit: Removing client PKInstallDaemonClient pid=6702, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Feb  3 15:13:07 camelopers-MacBook-Pro installd[304]: PackageKit: Done with sandbox removals
Feb  3 15:13:07 camelopers-MacBook-Pro Installer[6702]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Feb  3 15:13:07 camelopers-MacBook-Pro Installer[6702]: IFDInstallController E3454AA0 state = 8
Feb  3 15:13:07 camelopers-MacBook-Pro Installer[6702]: Displaying 'Install Failed' UI.
Feb  3 15:13:07 camelopers-MacBook-Pro Installer[6702]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
Feb  3 15:15:54 camelopers-MacBook-Pro Installer[6702]: LSSharedFileListCreate Using modern implementation for list: com.apple.LSSharedFileList.FavoriteItems
Feb  3 15:15:54 camelopers-MacBook-Pro Installer[6702]: -[SFLListManager listWithIdentifier:] List identifier: com.apple.LSSharedFileList.FavoriteItems
Feb  3 15:15:54 camelopers-MacBook-Pro Installer[6702]: __37-[SFLListManager listWithIdentifier:]_block_invoke Allocated list: com.apple.LSSharedFileList.FavoriteItems : <SFLList: 0x7f98e34c52f0>
Feb  3 15:15:54 camelopers-MacBook-Pro Installer[6702]: LSSharedFileListCreate Using modern implementation for list: com.apple.LSSharedFileList.ProjectsItems
Feb  3 15:15:54 camelopers-MacBook-Pro Installer[6702]: -[SFLListManager listWithIdentifier:] List identifier: com.apple.LSSharedFileList.ProjectsItems
Feb  3 15:15:54 camelopers-MacBook-Pro Installer[6702]: __37-[SFLListManager listWithIdentifier:]_block_invoke Allocated list: com.apple.LSSharedFileList.ProjectsItems : <SFLList: 0x7f98e5d2c480>
Feb  3 15:15:54 camelopers-MacBook-Pro Installer[6702]: __37-[SFLListManager listWithIdentifier:]_block_invoke109 Received state for list identifier: com.apple.LSSharedFileList.FavoriteItems
Feb  3 15:15:54 camelopers-MacBook-Pro Installer[6702]: -[SFLListObserver notify] Notifying observers for list com.apple.LSSharedFileList.FavoriteItems
Feb  3 15:15:54 camelopers-MacBook-Pro Installer[6702]: __37-[SFLListManager listWithIdentifier:]_block_invoke109 Received state for list identifier: com.apple.LSSharedFileList.ProjectsItems
Feb  3 15:15:54 camelopers-MacBook-Pro Installer[6702]: -[SFLListObserver notify] Notifying observers for list com.apple.LSSharedFileList.ProjectsItems
Feb  3 15:15:54 camelopers-MacBook-Pro Installer[6702]: LSSharedFileListCreate Using legacy implementation for list: com.apple.LSSharedFileList.FavoriteVolumes
Feb  3 15:15:59 camelopers-MacBook-Pro Installer[6702]: LSSharedFileListCreate Using legacy implementation for list: com.apple.LSSharedFileList.SharePoints
Feb  3 15:15:59 camelopers-MacBook-Pro Installer[6702]: LSSharedFileListCreate Using modern implementation for list: com.apple.LSSharedFileList.ApplicationRecentDocuments
Feb  3 15:15:59 camelopers-MacBook-Pro Installer[6702]: -[SFLListManager listWithIdentifier:] List identifier: com.apple.LSSharedFileList.ApplicationRecentDocuments/com.apple.installer
Feb  3 15:15:59 camelopers-MacBook-Pro Installer[6702]: __37-[SFLListManager listWithIdentifier:]_block_invoke Allocated list: com.apple.LSSharedFileList.ApplicationRecentDocuments/com.apple.installer : <SFLList: 0x7f98e5f66340>
Feb  3 15:15:59 camelopers-MacBook-Pro Installer[6702]: LSSharedFileListCreate Using legacy implementation for list: com.apple.LSSharedFileList.NetworkBrowser
Feb  3 15:15:59 camelopers-MacBook-Pro Installer[6702]: __37-[SFLListManager listWithIdentifier:]_block_invoke109 Received state for list identifier: com.apple.LSSharedFileList.ApplicationRecentDocuments/com.apple.installer
Feb  3 15:15:59 camelopers-MacBook-Pro Installer[6702]: -[SFLListObserver notify] Notifying observers for list com.apple.LSSharedFileList.ApplicationRecentDocuments/com.apple.installer

After i saw your answer at issue #88  i tried everything written in wiki. Still cannot install.

**Comment by 535064094** [comment]
try this?
https://github.com/535064094/535064094/wiki/iOSOpenDev-Install-(OSX-11-,Xcode-7)
