### ISSUE TITLE
Code 112: Failed install of iOSOpenDev 1.6.2 on Mac OSX 10.11.3 XCode Version 7.2.1 (7C1002)

### ISSUE THREAD

**Issue by 8a5** [kokoabim/iOSOpenDev#135]
I get a failed install of iOSOpenDev 1.6.2 on Mac OSX 10.11.3 XCode Version 7.2.1 (7C1002).

`Feb 19 13:46:37 MacBookPro installd[480]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “iOSOpenDev-1.6-2.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/***/Downloads/iOSOpenDev-1.6-2.pkg#iodsetup.pkg, PKInstallPackageIdentifier=com.iosopendev.iosopendev162.iod-setup.pkg, NSLocalizedDescription=An error occurred while running scripts from the package “iOSOpenDev-1.6-2.pkg”.} {
        NSFilePath = "./postinstall";
        NSLocalizedDescription = "An error occurred while running scripts from the package \U201ciOSOpenDev-1.6-2.pkg\U201d.";
        NSURL = "file://localhost/Users/Bas/Downloads/iOSOpenDev-1.6-2.pkg#iodsetup.pkg";
        PKInstallPackageIdentifier = "com.iosopendev.iosopendev162.iod-setup.pkg";
    }
`

**Comment by SeanXiao1988** [comment]
also get this error

**Comment by saighost** [comment]
so do I... +1

**Comment by 535064094** [comment]
maybe you could take look this solution,it might helps
https://github.com/535064094/535064094/wiki/iOSOpenDev-Install-(OSX-11-,Xcode-7)

**Comment by saighost** [comment]
谢谢，搞定了。

**Comment by ashish1405** [comment]
@535064094 your steps works, I've successfully installed iOSOpenDev on OSX 10.10 and XCode 7.2. There are few minor changes though in your steps. You can check the modified steps at https://gist.github.com/ashish1405/8744a1cf9d3d78af3a75559042f7eb54

**Comment by 535064094** [comment]
@ashish1405 Thanks you very much, can I update this to my blog?:)

**Comment by ashish1405** [comment]
@535064094 yes definitely, I also wrote you a mail regarding the same.

**Comment by 535064094** [comment]
@ashish1405  have a wonderful day:)

**Comment by kennedy0527** [comment]
I have followed solution step by step, but still got same error .....

is it possible because of 9.3 sdk doesn't include private framework ?

Mac OSX 10.11.3
Xcode Version 7.3

**Comment by DarrenDuXuan** [comment]
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by DarrenDuXuan** [comment]
has this error
