### ISSUE TITLE
Xcode 9.2 support! (fix for the moved Specifications folder) Instructions:

### ISSUE THREAD

**Issue by CokePokes** [kokoabim/iOSOpenDev#143]
(Note: iOSOpenDev will fail to install because it can't find the files in the Specifications folder & a folder for iPhoneSim. That's fine! You just need to add PrivateFrameworks manually! (You can get those from the theos github page!)

So after digging deep into why only dynamic libraries could be built with a iOSOpenDev template (because Specifications folder has moved) & Xcode now allows dynamic libraries to be built for iOS, you will need to add the entries from both iPhoneOSPackageTypes.plist & iPhoneOSProductTypes.plist to this Shared.plist file here:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/PrivatePlugIns/IDEiOSPlatformSupportCore.ideplugin/Contents/Resources/Shared.xcspec

You can find iPhoneOSPackageTypes.plist & iPhoneOSProductTypes.plist 
here: https://mega.nz/#!0mIwXSgI!mR1UFn3jd6R7EGR4X9yHtmTnYYGRNIQfsBMiPdlvMK8 

Hope that helps someone! Took f*cking forever to figure out.

**Comment by FivePixels** [comment]
What would it take to possibly make this work on Xcode 10?

(Referring to this: https://stackoverflow.com/a/51060778/5351192)
