### ISSUE TITLE
IOSOpendev Installation Error

### ISSUE THREAD

**Issue by fanliugen** [kokoabim/iOSOpenDev#30]
install log below:
Nov  4 17:43:23 fan.local installd[1116]: PackageKit: ----- Begin install -----
Nov  4 17:43:23 fan.local installd[1116]: PackageKit: request=PKInstallRequest <2 packages, destination=/>
Nov  4 17:43:23 fan.local installd[1116]: PackageKit: packages=(
        "PKLeopardPackage file://localhost/Users/ou/Desktop/iOSOpenDev-1.4-2.pkg#iodsetup.pkg",
        "PKLeopardPackage file://localhost/Users/ou/Desktop/iOSOpenDev-1.4-2.pkg#ioduninstall.pkg"
    )
Nov  4 17:43:23 fan.local installd[1116]: PackageKit: Extracting file://localhost/Users/ou/Desktop/iOSOpenDev-1.4-2.pkg#iodsetup.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/Cleanup At Startup/PKInstallSandboxManager/1.sandbox/Root/opt/iOSOpenDevSetup/bin, uid=0)
Nov  4 17:43:23 fan.local installd[1116]: PackageKit: Extracting file://localhost/Users/ou/Desktop/iOSOpenDev-1.4-2.pkg#ioduninstall.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/Cleanup At Startup/PKInstallSandboxManager/1.sandbox/Root/opt/iOSOpenDevUninstall/bin, uid=0)
Nov  4 17:43:23 fan.local installd[1116]: PackageKit: prevent user idle system sleep
Nov  4 17:43:23 fan.local installd[1116]: PackageKit: suspending backupd
Nov  4 17:43:23 fan.local installd[1116]: PackageKit: Executing script "./preinstall" in /private/tmp/PKInstallSandbox.u0o2MT/Scripts/com.iosopendev.iosopendev142.iod-setup.pkg.iwZTKW
Nov  4 17:43:23 fan.local install_monitor[1121]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Nov  4 17:43:23 fan.local installd[1116]: PackageKit: Executing script "./preinstall" in /private/tmp/PKInstallSandbox.u0o2MT/Scripts/com.iosopendev.iosopendev142.iod-uninstall.pkg.6OCD3z
Nov  4 17:43:23 fan.local installd[1116]: PackageKit: Shoving /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/Cleanup At Startup/PKInstallSandboxManager/1.sandbox/Root (1 items) to /
Nov  4 17:43:23 fan.local installd[1116]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.u0o2MT/Scripts/com.iosopendev.iosopendev142.iod-setup.pkg.iwZTKW
Nov  4 17:43:23 fan.local installd[1116]: ./postinstall: Running /opt/iOSOpenDevSetup/bin/iod-setup...
Nov  4 17:43:24 fan.local installd[1116]: ./postinstall: Downloading iOSOpenDev base from Github...
Nov  4 17:43:26 fan.local installd[1116]: ./postinstall: tar: Unrecognized archive format
Nov  4 17:43:26 fan.local installd[1116]: ./postinstall: tar: Error exit delayed from previous errors.
Nov  4 17:43:26 fan.local installd[1116]: ./postinstall: Failed to extract /private/tmp/PKInstallSandbox.u0o2MT/tmp/iod-setup.ZIk46hg4/file.tar.gz to /private/tmp/PKInstallSandbox.u0o2MT/tmp/iod-setup.SaFZ7FFK
Nov  4 17:43:26 fan.local install_monitor[1121]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Nov  4 17:43:26 fan.local installd[1116]: PackageKit: releasing backupd
Nov  4 17:43:26 fan.local installd[1116]: PackageKit: allow user idle system sleep
Nov  4 17:43:26 fan.local installd[1116]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “iOSOpenDev-1.4-2.pkg”." UserInfo=0x7fb3324cde10 {NSFilePath=./postinstall, NSURL=file://localhost/Users/ou/Desktop/iOSOpenDev-1.4-2.pkg#iodsetup.pkg, PKInstallPackageIdentifier=com.iosopendev.iosopendev142.iod-setup.pkg, NSLocalizedDescription=An error occurred while running scripts from the package “iOSOpenDev-1.4-2.pkg”.} {
        NSFilePath = "./postinstall";
        NSLocalizedDescription = "An error occurred while running scripts from the package \U201ciOSOpenDev-1.4-2.pkg\U201d.";
        NSURL = "file://localhost/Users/ou/Desktop/iOSOpenDev-1.4-2.pkg#iodsetup.pkg";
        PKInstallPackageIdentifier = "com.iosopendev.iosopendev142.iod-setup.pkg";
    }
Nov  4 17:43:26 fan.local Installer[1105]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “iOSOpenDev-1.4-2.pkg”." UserInfo=0x7ffba48c8d80 {NSFilePath=./postinstall, NSURL=file://localhost/Users/ou/Desktop/iOSOpenDev-1.4-2.pkg#iodsetup.pkg, PKInstallPackageIdentifier=com.iosopendev.iosopendev142.iod-setup.pkg, NSLocalizedDescription=An error occurred while running scripts from the package “iOSOpenDev-1.4-2.pkg”.}
Nov  4 17:43:27 fan.local Installer[1105]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Nov  4 17:43:27 fan.local Installer[1105]: IFDInstallController A4840C40 state = 7
Nov  4 17:43:27 fan.local Installer[1105]: Displaying 'Install Failed' UI.
Nov  4 17:43:27 fan.local Installer[1105]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.

hope someone can help me .Thanks

**Comment by 8a5** [comment]
I have failed install of iOSOpenDev 1.6.2 on Mac OSX 10.11.3 XCode Version 7.2.1 (7C1002).

`Feb 19 13:46:37 MacBookPro installd[480]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “iOSOpenDev-1.6-2.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/***/Downloads/iOSOpenDev-1.6-2.pkg#iodsetup.pkg, PKInstallPackageIdentifier=com.iosopendev.iosopendev162.iod-setup.pkg, NSLocalizedDescription=An error occurred while running scripts from the package “iOSOpenDev-1.6-2.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201ciOSOpenDev-1.6-2.pkg\U201d.";
	    NSURL = "file://localhost/Users/Bas/Downloads/iOSOpenDev-1.6-2.pkg#iodsetup.pkg";
	    PKInstallPackageIdentifier = "com.iosopendev.iosopendev162.iod-setup.pkg";
	}
`
